version: 0.2

phases:
  install:
    commands:
      - echo "=== FASE INSTALL: Instalando dependencias ==="
      - pip install -r app/requirements.txt pytest
  pre_build:
    commands:
      - echo "=== FASE PRE_BUILD: Ejecutando pruebas unitarias ==="
      - cd app
      - pytest tests/ -v
      - cd ..
  build:
    commands:
      - echo "=== FASE BUILD: Construyendo imagen Docker ==="
      - docker build -t mi-app-flask app/
  post_build:
    commands:
      - echo "=== FASE POST_BUILD: Build completado exitosamente ==="
artifacts:
  files:
    - '**/*'